# **LA_03_1 Permutations**

In [ ]:
import numpy as np

#### **Permutations**

**Definition**  An (algebraic) permutation of $n$ elements is a bijection (i.e. on-to-one map) from the set $\{1,2,3,\dots, n\}$ to itself.

For the permutation $\sigma$ it means that map images $\sigma(1), \dots, \sigma(n)$ are all the distinct elements from  $\{1,2,3,\dots, n\}$.

The permutation $\sigma$ can be given as  $\displaystyle \sigma =\begin{pmatrix}
1 & 2 & \dotsc  & n\\
\sigma ( 1) & \sigma ( 2) & \dotsc  & \sigma ( n)
\end{pmatrix}$, where $\sigma(1), \dots, \sigma(n)$ in the second raw is a combinatorial permutation of $1,2, \dots, n$, i.e., just another rearrangment of these elements. That is why algebraic and combinatorial permutations are usually not distinguished. But we will refer to permutations as maps.

The columns of the permutation can be given in any order.

*Example.*  $\sigma =\begin{pmatrix}
1 & 2 & 3 & 4\\
3 & 2 & 4 &  1
\end{pmatrix} = \begin{pmatrix}
2 & 4 & 3 & 1\\
2 & 1 & 4 & 3
\end{pmatrix}.$



$S_n$ is used to denote the set of all permutations of $n$ elements.

Obviously $|S_n|=n!$.


---
#### **Coding sample: permutations generation**


In [ ]:
from itertools import permutations

#construct all the permutation of 1, 2, 3
permutations_list = list(permutations([1, 2, 3]))
print('Permutations as tuples:', permutations_list)

def perm_to_dict(tuple):
  '''
  Convert tuple-permutation into a dictionary
  Args:
      tuple: should be a permutation of  1, 2, ... ,n.
  Returns:
      A dictionary representing the permutation. Keys are the elements being permuted, and values are their images.
  '''
  return {i+1: tuple[i] for i in range(len(tuple))}

print('Permutations as dicts(maps):', [perm_to_dict(t) for t in permutations_list])

Permutations as tuples: [(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]
Permutations as dicts(maps): [{1: 1, 2: 2, 3: 3}, {1: 1, 2: 3, 3: 2}, {1: 2, 2: 1, 3: 3}, {1: 2, 2: 3, 3: 1}, {1: 3, 2: 1, 3: 2}, {1: 3, 2: 2, 3: 1}]



---


#### **Permutation multiplication**

**Definition.** We can define the multiplication of permutations as a composition of underlying maps: $\sigma\tau(j)=\sigma(\tau(j))$ for every $j=1,2,\dots, n.$

*Example.* $\sigma\tau = \left(\begin{array}{ c c c c c }
1 & 2 & 3 & 4 & 5\\
4 & 2 & 1 & 5 & 3
\end{array}\right)\left(\begin{array}{ c c c c c }
1 & 2 & 3 & 4 & 5\\
1 & 3 & 5 & 4 & 2
\end{array}\right) =  \left(\begin{array}{ c c c c c }
1 & 2 & 3 & 4 & 5\\
4 & 1 & 3 & 5 & 2
\end{array}\right)$.

Note that due to composition nature multiplication is done from right to left (inner map first), e.g. $\sigma\tau(2)=\sigma(\tau(2))=\sigma(3)=1$.

Also note that permutation multiplication is not commutative in general.

**Theorem [on permutation multiplication properties].**
1. *Associativity*. $\sigma(\tau\rho)=(\sigma\tau)\rho$.
2. *Neutral element*. For $id = \left(\begin{array}{ c c c c }
1 & 2 & \dots & n \\
1 & 2 & \dots & n
\end{array}\right)$ and every $\sigma$ it holds $\sigma id = id\sigma=\sigma$.
3. *Inverse*. There is an inverse permutation $\sigma^{-1}$ for every $\sigma\in S_n$: $\sigma^{-1}\sigma=\sigma\sigma^{-1}=id$.

The theorem states that $S_n$ is a group with multiplication operation. It is called the *symmetrical* group.


---
#### **Coding sample: permutation multiplication**

In [ ]:
# generated by AI

def permutation_composition(sigma, tau):
    """
    Computes the composition of two permutations.

    Args:
        sigma: A dictionary representing the first permutation. Keys are the elements being permuted, and values are their images.
        tau: A dictionary representing the second permutation.

    Returns:
        A dictionary representing the composition of sigma and tau (sigma(tau(x))).
        Returns None if the permutations are not compatible (different domains).
    """

    # Check for compatible domains.
    if set(sigma.keys()) != set(tau.keys()):
        return None

    composed_permutation = {}
    for element in sigma:
        composed_permutation[element] = sigma[tau[element]]

    return composed_permutation




---


#### **Cycles and transpositions**

**Definition.** A *cycle* of length $l\geq 2$ is a permutation $\sigma$ for which there exist $j_1, j_2, \dots, j_l$, such as $\sigma(j_1)=j_2, \sigma(j_2)=j_3, \dots , \sigma(j_{l-1})=j_l, \sigma(j_l)=j_1$ and other elements are fixed ( i.e. $\sigma(j)=j$ for other $j$).

A cycle of length 2 is called a *transposition*.

Cycle of $j_1, \dots, j_l$ is usually written as $(j_1, j_2, \dots, j_l)$. It also can start from any other its element, that is $(j_1, j_2, \dots, j_l)=(j_2, j_3, \dots, j_l, j_1)=\dots=(j_l, j_1, \dots, j_2)$.

Two cycles with different sets of elements are called *independent*. Independent cycles always commute:

$(i_1, \dots, i_l)(j_1, \dots, j_s)=(j_1, \dots, j_s)(i_1, \dots, i_l)$ if $\{i_1, \dots, i_l\}\cap \{j_1, \dots, j_s\}=\emptyset$.

**Theorem [on independent cycles decomposition].** Each permutation can be uniquely (up to the order of cycles and the way to write down the cycles) given as a product of independent cycles.

*Example.* $\left(\begin{array}{ c c c c c c c c c}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9\\
4 & 2 & 1 & 5 & 6 & 3 & 8 & 7 & 9
\end{array}\right) = (14563)(78) = (14563)(78)(2)(9)$.
Last decomposition also includes the fixed elements (2, 9), which are not the cycles but usually are considered for completeness and utility.  


**Theorem [on transposition decomposition].** Each permutation can be given as a product of transpositions.

Note that the uniqueness of decomposition and the independence of transposition are not stated.

*Example.* $\left(\begin{array}{ c c c c c c c c c}
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9\\
4 & 2 & 1 & 5 & 6 & 3 & 8 & 7 & 9
\end{array}\right) = (14563)(78) = (13)(16)(15)(14)(78)$.


#### **Parity of permutations**

**Definition** For a (combinatorial) permutation $i_1, i_2, \dots, i_n$ of $\{1, 2, \dots , n\}$ an *inversion* is a pair $(i_k, i_j)$, such as $k < j $ and $i_k > i_j$. The number of inversions for (algebraic) permutation $\sigma$ for both its rows is denoted by $I(\sigma)$.

*Example.* For $\sigma =\begin{pmatrix}
1 & 2 & 3 & 4\\
3 & 2 & 4 &  1
\end{pmatrix}$ the number of inversions $I(\sigma) = 4$ ((3,2), (3,1), (2,1), (4,1))  
For the same permutation $\begin{pmatrix}
2 & 4 & 3 & 1\\
2 & 1 & 4 & 3
\end{pmatrix}$ but written down in another way $I(\sigma) = 4 + 2 = 6$ (4 for upper row and 2 -- for lower).

**Theorem [on permutation parity].** Consider a permutation $\sigma\in S_n$.

Let
$\sigma = \sigma_1\dots\sigma_s$  be its decomposition into independent cycles and fixed elements;

$\sigma = \tau_1\dots\tau_k$ be its decomposition into transpositions.


Then $I(\sigma), d=n-s, k$ have the same parity (are all even or are all odd).

The Theorem particularly states that the parity of the number of inversions is the same for all ways to write down the permutation in two-rows notation. And all the decompositions into transpositions have either always even or always odd number of transpositions.

*Example.*  $\sigma =\begin{pmatrix}
1 & 2 & 3 & 4\\
3 & 2 & 4 &  1
\end{pmatrix} = (134)(2) = (14)(13).$

$I(\sigma) = 4$, $d = 4 -2 =2$, $k = 2$ are all even.

**Definition.** The number $d=n-s$, where $s$ is a number of independent cycles and fixed elements of $\sigma\in S_n$ is called a *decrement* of $\sigma$.

**Definition.** A sign of a permutation $\sigma$ is $sgn(\sigma)=(-1)^{I(\sigma)}=(-1)^d=\displaystyle \begin{cases}
+1,\ \sigma \ is\ even;\\
-1,\ \sigma \ is\ odd.
\end{cases}$

#### **Permutation matrices**

Permutations can also be given as matrices.

**Definition.** A square $n\times n$ matrix $P_{\sigma}=(p_{ij})$ is a *permutation matrix*, if there exist $\sigma\in S_n$ such as $p_{ij} =  \begin{cases}
1, \ \sigma(j) = i;\\
0, \ otherwise.
\end{cases}$

**Proposition [on permutation matrix multiplication].**

$P_{\sigma}P_{\tau} = P_{\sigma\tau}$.



---

#### **Coding sample: permutation matrices.**

In [ ]:
def permutation_matrix(sigma):
  """
  Construct permutation matrix by permutation sigma

  Args:
        sigma: A dictionary representing the permutation. Keys are the elements being permuted, and values are their images.

  Returns:
        P: A numpy array representing the permutation matrix.
  """
  P = np.zeros((len(sigma), len(sigma)), dtype=int)
  for i in sigma:
    P[sigma[i]-1, i-1] = 1
  return P

sigma = {1: 1, 2: 3, 3: 2}
rho = {1: 2, 2: 3, 3: 1}
P_sigma = permutation_matrix(sigma)
P_rho = permutation_matrix(rho)

sigma_rho = permutation_composition(sigma, rho)
P_sigma_rho = permutation_matrix(sigma_rho)
P = P_sigma @ P_rho

print(f'''sigma: {sigma}, P_sigma: \n {P_sigma} \n ''')
print(f'''rho: {rho}, P_rho:\n  {P_rho} \n''')
print(f'''sigma_rho: {sigma_rho}, P_sigma_rho: \n {P_sigma_rho},\n P_sigma P_rho \n {P}''')


sigma: {1: 1, 2: 3, 3: 2}, P_sigma: 
 [[1 0 0]
 [0 0 1]
 [0 1 0]] 
 
rho: {1: 2, 2: 3, 3: 1}, P_rho:
  [[0 0 1]
 [1 0 0]
 [0 1 0]] 

sigma_rho: {1: 3, 2: 2, 3: 1}, P_sigma_rho: 
 [[0 0 1]
 [0 1 0]
 [1 0 0]],
 P_sigma P_rho 
 [[0 0 1]
 [0 1 0]
 [1 0 0]]




---

